# Copyright (C) 2025 Pedro Henrique / phkaiser13
#
# File: k8s/crd/ph.io_phgitsyncjobs.yaml
#
# This file defines the Custom Resource Definition (CRD) for the PhgitSyncJob
# resource. This CRD provides a declarative way to trigger a synchronization
# of Kubernetes manifests from a Git repository to a cluster.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: phgitsyncjobs.ph.io
spec:
  group: ph.io
  scope: Namespaced
  names:
    plural: phgitsyncjobs
    singular: phgitsyncjob
    kind: PhgitSyncJob
    shortNames:
      - pgsj
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - path
                - cluster
              properties:
                path:
                  type: string
                  description: "The local path to the Git repository containing the manifests."
                cluster:
                  type: string
                  description: "The name of the target cluster to sync to."
                apply:
                  type: boolean
                  description: "If true, directly apply the manifests. If false, performs a dry-run."
                  default: false
                force:
                  type: boolean
                  description: "If true, force-apply the manifests, overriding conflicts."
                  default: false
                skipSignatureVerification:
                  type: boolean
                  description: "If true, skip commit signature verification."
                  default: false
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Syncing", "Succeeded", "Failed"]
                  description: "The current phase of the sync job."
                startTime:
                  type: string
                  format: date-time
                completionTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastUpdateTime:
                        type: string
                        format: date-time
                      message:
                        type: string
