[package]
name = "k8s_info"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] 

[dependencies]
kube = "1.1.0"
k8s-openapi = { version = "0.25.0", features = ["v1_28"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
libc = "0.2" 
anyhow = "1.0" 