name: Build VS Code Extension (vscode-peitch)

on:
  push:
    paths:
      - 'vscode-peitch/**'
  pull_request:
    paths:
      - 'vscode-peitch/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package VSIX
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'     # ajuste para a versão que seu projeto usa (ex: '20' ou '18')
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./vscode-peitch
        run: npm ci

      - name: Build (if present)
        working-directory: ./vscode-peitch
        run: npm run build --if-present

      - name: Run tests (if any)
        working-directory: ./vscode-peitch
        run: npm test --if-present
        continue-on-error: true

      - name: Install vsce (packager)
        run: npm install -g vsce

      - name: Package extension (VSIX)
        working-directory: ./vscode-peitch
        run: |
          # vsce normalmente cria <nome>-<versão>.vsix ou você pode usar -o para nome fixo
          vsce package -o vscode-peitch.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-peitch-vsix
          path: |
            vscode-peitch.vsix
            vscode-peitch/*.vsix
            vscode-peitch/**/out/*.vsix
          retention-days: 30
